export const PLACE_ORDER_REQUEST="PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS="PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL="PLACE_ORDER_FAIL"
export const PLACE_ORDER_RESET="PLACE_ORDER_RESET"

export const PAY_ORDER_REQUEST="PAY_ORDER_REQUEST"
export const PAY_ORDER_SUCCESS="PAY_ORDER_SUCCESS"
export const PAY_ORDER_FAIL="PAY_ORDER_FAIL"
export const PAY_ORDER_RESET="PAY_ORDER_RESET"

export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL"

export const ORDER_LIST_REQUEST="ORDER_LIST_REQUEST"
export const ORDER_LIST_SUCCESS="ORDER_LIST_SUCCESS"
export const ORDER_LIST_FAIL="ORDER_LIST_FAIL"